export interface StudyGuideFaq {
  question: string;
  answer: string;
}

export interface StudyGuide {
  slug: string;
  title: string;
  description: string;
  category: string;
  department: string;
  author: string;
  updatedAt: string;
  readingMinutes: number;
  summary: string;
  whyItMatters: string;
  keyTopics: string[];
  practicePlan: string[];
  commonMistakes: string[];
  examRoomTips: string[];
  faqs: StudyGuideFaq[];
  relatedSlugs: string[];
}

export const SITE_URL = 'https://padhakuportal.in';
export const SITE_NAME = 'PadhakuPortal';
export const DEFAULT_AUTHOR = 'PadhakuPortal Editorial Team';
export const CONTENT_UPDATED_AT = '2026-05-18';

export const STUDY_GUIDES: StudyGuide[] = [
  {
    slug: 'data-structures-pyq-strategy',
    title: 'Data Structures PYQ Strategy for Semester Exams',
    description: 'A practical plan for using previous year questions to revise arrays, linked lists, stacks, queues, trees, graphs, and hashing.',
    category: 'Computer Science',
    department: 'Computer Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Data Structures is a scoring subject when you revise it as a collection of patterns instead of a long list of definitions. Most semester papers test how well you can trace operations, compare data structures, write core algorithms, and calculate time complexity. PYQs help because repeated question styles reveal which topics need exact steps and which topics need conceptual clarity.',
    whyItMatters: 'Students often spend too much time memorizing code and too little time practicing dry runs. A better approach is to create a pattern notebook: insertion and deletion cases for linked lists, stack and queue applications, tree traversals, graph traversal tables, hashing collision handling, and short complexity notes. This makes revision active and keeps answers structured under time pressure.',
    keyTopics: ['Array operations, sparse matrices, and polynomial representation', 'Linked list insertion, deletion, reversal, and circular list cases', 'Stack applications such as infix to postfix conversion and expression evaluation', 'Queue variants including circular queue, deque, and priority queue', 'Binary trees, BST operations, traversals, heaps, and graph traversal', 'Hash tables, collision resolution, and asymptotic complexity'],
    practicePlan: ['Collect the last five available papers and tag every question by topic.', 'Solve tracing questions on paper without looking at notes, then compare steps.', 'Write pseudocode for the ten most repeated operations until the structure is automatic.', 'Create a one-page complexity table for searching, insertion, deletion, and traversal.', 'Practice one mixed mock test with strict timing and mark weak patterns for review.'],
    commonMistakes: ['Writing code without explaining edge cases such as an empty list or single-node list.', 'Confusing BFS with DFS when the graph is represented as an adjacency matrix.', 'Forgetting to show stack contents during expression conversion problems.', 'Using Big O notation without stating what n represents.', 'Skipping diagrams for tree and heap operations even when they make the answer clearer.'],
    examRoomTips: ['Begin with questions where you can draw the data structure state after each operation.', 'For algorithms, write the idea, pseudocode, dry run, and complexity in that order.', 'If the code is long, use clean pseudocode and label edge cases instead of crowding the page.', 'Reserve five minutes to recheck traversal sequences and index-based array operations.'],
    faqs: [
      { question: 'Should I memorize full C or Java programs?', answer: 'Memorize the logic and core steps, not a full program by heart. Most exam answers are stronger when they include clear pseudocode, a diagram, a dry run, and complexity.' },
      { question: 'How many PYQs are enough for Data Structures?', answer: 'Five years is a good minimum. If your university repeats patterns heavily, also solve model papers and class tests for the same operations.' },
    ],
    relatedSlugs: ['object-oriented-programming-guide', 'operating-systems-core-concepts', 'dbms-sql-normalization-guide'],
  },
  {
    slug: 'engineering-mathematics-revision-plan',
    title: 'Engineering Mathematics Revision Plan',
    description: 'A topic-wise revision guide for calculus, matrices, transforms, differential equations, probability, and numerical methods.',
    category: 'Engineering Mathematics',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Engineering Mathematics rewards consistent problem practice more than last-day theory reading. The same ideas appear in different forms: solving a differential equation, applying a transform, finding eigenvalues, or using a numerical method. The goal is to recognize the method quickly and then carry out calculations without avoidable arithmetic mistakes.',
    whyItMatters: 'A strong math answer is not only the final value. It shows the selected method, assumptions, formula substitution, and clean intermediate steps. When you revise with this structure, partial marking becomes easier and panic reduces because every problem has an entry point.',
    keyTopics: ['Matrices, rank, eigenvalues, eigenvectors, and diagonalization', 'Differential equations and applications to engineering systems', 'Laplace and Fourier transforms with standard properties', 'Multiple integration, vector calculus, gradient, divergence, and curl', 'Probability distributions, correlation, regression, and sampling basics', 'Numerical methods such as bisection, Newton-Raphson, interpolation, and Simpson rules'],
    practicePlan: ['Create a formula sheet grouped by method rather than by chapter order.', 'Solve three examples per method: direct, tricky, and previous-year style.', 'Maintain an error log for sign mistakes, limits, units, and calculator slips.', 'Revise standard transform pairs and derivative/integral properties daily for one week.', 'Take one timed mixed test where you must choose methods without chapter hints.'],
    commonMistakes: ['Starting a problem before checking conditions such as convergence or interval limits.', 'Dropping constants during integration or applying transform shifting rules incorrectly.', 'Writing only the answer for numerical methods without an iteration table.', 'Mixing row operations and column operations while finding rank.', 'Skipping units or interpretation when the question is application based.'],
    examRoomTips: ['Write the known formula before substitution so the evaluator can follow your method.', 'Box intermediate results in long calculations to make rechecking faster.', 'If arithmetic becomes messy, continue symbolically for one line before calculating.', 'Use graph or table format when numerical method questions ask for iterations.'],
    faqs: [
      { question: 'What should I revise first if time is low?', answer: 'Start with high-frequency methods from PYQs, especially matrices, transforms, differential equations, and numerical methods. These usually offer predictable marks.' },
      { question: 'How do I reduce calculation mistakes?', answer: 'Keep an error log and re-solve only the mistaken step the next day. Repetition of corrected mistakes is more useful than solving many fresh problems carelessly.' },
    ],
    relatedSlugs: ['signals-systems-problem-solving', 'control-systems-root-locus', 'study-planner-active-recall'],
  },
  {
    slug: 'thermodynamics-numerical-practice',
    title: 'Thermodynamics Numerical Practice Guide',
    description: 'A step-by-step approach to thermodynamics numericals, property tables, laws, cycles, entropy, and common exam mistakes.',
    category: 'Mechanical Engineering',
    department: 'Mechanical Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Thermodynamics becomes manageable when every numerical is treated like a small model of a system. Before using formulas, identify the system, boundary, process, known values, unknown values, assumptions, and units. This prevents the most common problem: applying a correct equation to the wrong situation.',
    whyItMatters: 'Many thermodynamics questions award marks for method even when the final answer has minor arithmetic variation. A neat solution with a process diagram, sign convention, property values, and unit consistency is much stronger than a formula-only answer.',
    keyTopics: ['Zeroth, first, and second laws of thermodynamics', 'Closed systems, open systems, work, heat, and internal energy', 'Properties of pure substances and use of steam tables', 'Entropy, availability, irreversibility, and efficiency', 'Carnot, Otto, Diesel, Brayton, and Rankine cycles', 'Psychrometric basics and refrigeration cycle calculations'],
    practicePlan: ['Make a table of standard assumptions for each cycle and process.', 'Practice reading property tables and writing the exact row or interpolation used.', 'Solve one problem daily with a full diagram and unit check.', 'Group PYQs by cycle type and solve repeated patterns together.', 'After every solution, write one sentence interpreting whether the result is physically reasonable.'],
    commonMistakes: ['Using gauge pressure where absolute pressure is required.', 'Ignoring sign convention for work done by or on the system.', 'Mixing kJ, J, kg, and kW units in the same equation.', 'Reading saturated values when the state is superheated or compressed.', 'Forgetting to state assumptions such as steady flow or negligible kinetic energy.'],
    examRoomTips: ['Draw the process diagram first even if it is simple.', 'Write all known data in a column before equations.', 'Keep property table values visible and label them with state numbers.', 'Check whether efficiency or COP should be less than or greater than one.'],
    faqs: [
      { question: 'Are steam tables necessary for every problem?', answer: 'No. Use tables when the state involves phase-change data or property lookup. For ideal gas problems, gas equations and specific heat relations may be enough.' },
      { question: 'How do I identify the right cycle?', answer: 'Look for keywords: spark ignition suggests Otto, compression ignition suggests Diesel, gas turbine suggests Brayton, steam power plant suggests Rankine, and refrigerator or heat pump suggests vapor compression.' },
    ],
    relatedSlugs: ['fluid-mechanics-exam-prep', 'machine-design-safe-practice', 'strength-of-materials-formula-map'],
  },
  {
    slug: 'circuit-analysis-semester-revision',
    title: 'Circuit Analysis Semester Revision Guide',
    description: 'A revision path for DC circuits, AC circuits, network theorems, transient response, resonance, and phasor practice.',
    category: 'Electrical Engineering',
    department: 'Electrical Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Circuit Analysis is best revised through repeatable solving habits. Whether the question uses KCL, KVL, Thevenin, Norton, superposition, or phasors, the answer should begin with a clean circuit redraw and clear reference directions. Once directions are chosen, consistent equations usually lead to marks even if the arithmetic is lengthy.',
    whyItMatters: 'Students lose marks when they jump between sign conventions or skip the conversion from time-domain to phasor-domain quantities. A disciplined layout keeps complex numbers, units, and polar or rectangular forms from becoming tangled.',
    keyTopics: ['Ohm law, Kirchhoff laws, source transformation, and mesh analysis', 'Nodal analysis, dependent sources, and supernode or supermesh cases', 'Thevenin, Norton, maximum power transfer, and reciprocity theorem', 'Sinusoidal steady state, impedance, admittance, and phasor diagrams', 'Transient response of RC, RL, and RLC circuits', 'Series and parallel resonance with bandwidth and quality factor'],
    practicePlan: ['Redraw every circuit with chosen current directions and node labels.', 'Solve five mesh and five nodal problems before moving to theorems.', 'Practice converting complex numbers between rectangular and polar form.', 'Keep a mini-sheet of impedance relations for R, L, and C.', 'Take one timed theorem-only quiz and one timed AC-circuit quiz.'],
    commonMistakes: ['Changing current direction midway without changing signs.', 'Treating dependent sources like independent sources during source transformation.', 'Forgetting that capacitors and inductors behave differently in DC steady state.', 'Mixing RMS and peak values in AC power calculations.', 'Not drawing a phasor diagram when the question expects one.'],
    examRoomTips: ['Label node voltages before writing nodal equations.', 'Use a separate line for complex arithmetic so the main solution stays readable.', 'For theorem problems, show the open-circuit voltage and equivalent resistance clearly.', 'Check units: ohms, siemens, volts, amps, watts, and vars are not interchangeable.'],
    faqs: [
      { question: 'Which method is faster: mesh or nodal?', answer: 'Choose based on the circuit. Nodal is often faster when there are many current sources; mesh is often faster for planar circuits with voltage sources.' },
      { question: 'How should I revise transients?', answer: 'Memorize the final-value pattern, time constant, and standard exponential form. Then practice identifying initial and final conditions from the circuit.' },
    ],
    relatedSlugs: ['power-systems-revision-guide', 'control-systems-root-locus', 'signals-systems-problem-solving'],
  },
  {
    slug: 'digital-electronics-exam-guide',
    title: 'Digital Electronics Exam Guide',
    description: 'A focused guide for Boolean algebra, K-maps, combinational circuits, sequential circuits, counters, registers, and timing basics.',
    category: 'Electronics',
    department: 'Electronics and Communication',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Digital Electronics is a high-scoring subject because many questions follow a fixed process: simplify logic, draw the circuit, build a truth table, or analyze a timing sequence. The best revision strategy is to practice each process until the layout becomes automatic.',
    whyItMatters: 'Marks are often lost due to small presentation errors: missing variables in a truth table, grouping K-map cells incorrectly, or drawing a flip-flop response without marking clock edges. Clean diagrams and stepwise minimization make answers easier to evaluate.',
    keyTopics: ['Number systems, codes, complements, and binary arithmetic', 'Boolean algebra identities, De Morgan law, and logic gates', 'K-map minimization for SOP and POS forms', 'Adders, subtractors, multiplexers, demultiplexers, encoders, and decoders', 'Latches, flip-flops, registers, and counters', 'State tables, excitation tables, race conditions, and basic timing diagrams'],
    practicePlan: ['Practice conversions between binary, decimal, octal, hexadecimal, and BCD.', 'Solve K-map problems with 2, 3, and 4 variables using both SOP and POS forms.', 'Draw at least one circuit for each combinational building block.', 'Create a flip-flop excitation table sheet and revise it daily before exams.', 'Solve sequential circuit PYQs by writing present state, next state, and output clearly.'],
    commonMistakes: ['Making invalid K-map groups or missing wraparound adjacency.', 'Confusing encoder and decoder input-output direction.', 'Forgetting propagation delay in timing questions.', 'Mixing active-high and active-low notation.', 'Writing a final expression without drawing the requested logic circuit.'],
    examRoomTips: ['Use pencil for K-map grouping so corrections stay neat.', 'Label MSB and LSB in number-system questions.', 'For counters, write the sequence first and then draw flip-flop transitions.', 'Show both simplified expression and circuit if the question asks for implementation.'],
    faqs: [
      { question: 'Are K-maps more important than Boolean algebra?', answer: 'Both matter, but K-maps are often quicker in exams. Boolean laws still help when the question asks for proof or algebraic simplification.' },
      { question: 'How do I avoid mistakes in sequential circuits?', answer: 'Always create a table. State-based questions become much easier when present state, input, next state, and output are separated.' },
    ],
    relatedSlugs: ['microprocessors-8086-revision', 'communication-systems-exam-guide', 'signals-systems-problem-solving'],
  },
  {
    slug: 'operating-systems-core-concepts',
    title: 'Operating Systems Core Concepts Guide',
    description: 'A structured guide to processes, scheduling, memory management, synchronization, deadlocks, file systems, and OS numericals.',
    category: 'Computer Science',
    department: 'Computer Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Operating Systems questions mix theory with small numericals. The subject becomes easier when you connect every topic to the main job of an OS: managing CPU time, memory, files, devices, and safe execution among multiple processes.',
    whyItMatters: 'Many answers fail because they describe a term but do not show the mechanism. For example, scheduling needs a Gantt chart, paging needs address translation, and synchronization needs a clear explanation of shared resources and critical sections.',
    keyTopics: ['Process states, process control block, threads, and context switching', 'CPU scheduling algorithms with waiting time and turnaround time', 'Inter-process communication, critical section, semaphores, and monitors', 'Deadlock conditions, prevention, avoidance, and Banker algorithm', 'Paging, segmentation, virtual memory, and page replacement algorithms', 'File allocation, directory structures, disk scheduling, and protection'],
    practicePlan: ['Create comparison tables for scheduling, memory allocation, and page replacement algorithms.', 'Solve scheduling problems with Gantt charts until averages are consistent.', 'Practice Banker algorithm and page replacement tables from PYQs.', 'Write short answers for critical section, deadlock, and virtual memory in your own words.', 'Revise file-system diagrams and disk scheduling tracks before the exam.'],
    commonMistakes: ['Forgetting arrival time in scheduling calculations.', 'Mixing waiting time and turnaround time formulas.', 'Applying FIFO page replacement steps without checking current frames.', 'Listing deadlock conditions but not explaining why all four are necessary.', 'Writing generic definitions without diagrams or tables.'],
    examRoomTips: ['Use tables for numerical algorithms; they make partial marks easier.', 'In theory answers, start with purpose, then mechanism, then advantage or limitation.', 'For deadlock questions, explicitly mention resource allocation and circular wait.', 'Check average calculations twice because one arithmetic slip can affect the final answer.'],
    faqs: [
      { question: 'Which OS numericals are most important?', answer: 'Scheduling, page replacement, Banker algorithm, and disk scheduling are usually worth repeated practice because they appear in predictable formats.' },
      { question: 'How much coding is needed for OS exams?', answer: 'Most semester OS exams focus on concepts and algorithms. Pseudocode may be useful for synchronization or scheduling, but full programs are rarely the main requirement.' },
    ],
    relatedSlugs: ['data-structures-pyq-strategy', 'dbms-sql-normalization-guide', 'computer-networks-last-week-plan'],
  },
  {
    slug: 'dbms-sql-normalization-guide',
    title: 'DBMS SQL and Normalization Guide',
    description: 'A student-friendly guide for ER models, relational algebra, SQL queries, normalization, transactions, and indexing basics.',
    category: 'Computer Science',
    department: 'Computer Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'DBMS is easier when you treat it as two linked skills: designing reliable data models and querying them correctly. ER diagrams, keys, normalization, SQL, transactions, and indexing all support the same goal: storing data in a way that stays accurate and useful.',
    whyItMatters: 'A good DBMS answer is precise. It names keys, shows relationships, states functional dependencies, and writes SQL with correct joins and grouping. Vague answers can look correct at first but lose marks when constraints or edge cases are missing.',
    keyTopics: ['ER diagrams, entity sets, relationships, cardinality, and participation', 'Relational model, keys, constraints, and relational algebra', 'SQL SELECT, WHERE, JOIN, GROUP BY, HAVING, subqueries, and views', 'Functional dependencies and normalization up to BCNF', 'Transactions, ACID properties, schedules, serializability, and concurrency control', 'Indexing, hashing, B trees, and query processing basics'],
    practicePlan: ['Draw ER diagrams from small real-world scenarios and convert them into relations.', 'Practice SQL joins with at least three tables, including aggregate queries.', 'List functional dependencies before attempting normalization.', 'Solve schedule problems by checking conflicts and serial equivalence.', 'Make a short comparison sheet for 1NF, 2NF, 3NF, and BCNF.'],
    commonMistakes: ['Confusing primary key, candidate key, and foreign key.', 'Using WHERE instead of HAVING for aggregate filters.', 'Normalizing without clearly writing functional dependencies.', 'Forgetting total or partial participation in ER diagrams.', 'Explaining ACID as a list without examples.'],
    examRoomTips: ['For SQL, write table aliases and qualify columns when multiple tables are involved.', 'In normalization answers, show each decomposition step and why it is needed.', 'For ER diagrams, label cardinality and participation clearly.', 'When stuck on a query, write the expected output columns first and build the query backward.'],
    faqs: [
      { question: 'Is relational algebra still important if SQL is asked?', answer: 'Yes. Relational algebra builds the logic behind SQL and often appears as short conversion or expression questions.' },
      { question: 'How do I know if a table is in 3NF?', answer: 'Check dependencies. For every non-trivial dependency X to A, X should be a superkey, or A should be a prime attribute. Work through examples until this test feels natural.' },
    ],
    relatedSlugs: ['operating-systems-core-concepts', 'computer-networks-last-week-plan', 'data-structures-pyq-strategy'],
  },
  {
    slug: 'computer-networks-last-week-plan',
    title: 'Computer Networks Last Week Study Plan',
    description: 'A seven-day revision strategy for OSI/TCP-IP models, IP addressing, routing, transport protocols, DNS, and network security basics.',
    category: 'Computer Science',
    department: 'Computer Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Computer Networks has many terms, but exam questions usually revolve around layered responsibilities, addressing, routing decisions, error control, congestion control, and application protocols. The final week should focus on clear comparisons and small calculation practice.',
    whyItMatters: 'Layered answers help you avoid mixing concepts. If a question is about TCP, keep the answer in the transport layer. If it is about IP addressing, show subnet calculations clearly. This organization makes long answers more readable and reduces conceptual overlap.',
    keyTopics: ['OSI and TCP/IP models with layer-wise responsibilities', 'Framing, error detection, CRC, flow control, and MAC basics', 'IPv4 addressing, subnetting, CIDR, NAT, and IPv6 introduction', 'Routing algorithms, distance vector, link state, and routing protocols', 'TCP, UDP, congestion control, reliability, and connection management', 'DNS, HTTP, email protocols, network security, and firewalls'],
    practicePlan: ['Day 1: Revise models and create a layer-wise protocol table.', 'Day 2: Practice CRC, parity, and framing questions.', 'Day 3: Solve subnetting and CIDR problems until the steps are automatic.', 'Day 4: Compare routing algorithms and write their pros and limits.', 'Day 5: Practice TCP, UDP, congestion control, and socket basics.', 'Day 6 and 7: Solve mixed PYQs and revise diagrams.'],
    commonMistakes: ['Mixing OSI layer names with TCP/IP layer names without explanation.', 'Doing subnet calculations without writing the mask and block size.', 'Confusing flow control with congestion control.', 'Writing DNS or HTTP answers without explaining request-response flow.', 'Skipping diagrams for TCP handshake or routing updates.'],
    examRoomTips: ['Start layered questions with a compact table.', 'For subnetting, write binary only where it helps and keep the final answer in dotted decimal.', 'Use sequence diagrams for handshake and request-response questions.', 'When comparing protocols, include reliability, ordering, overhead, and use case.'],
    faqs: [
      { question: 'What is the fastest way to revise subnetting?', answer: 'Practice block-size recognition. Once you know the mask, network address, broadcast address, and host range become much faster.' },
      { question: 'Should I memorize all protocol port numbers?', answer: 'Memorize common ones such as HTTP, HTTPS, DNS, FTP, SMTP, POP3, and SSH. More important than numbers is knowing what each protocol does.' },
    ],
    relatedSlugs: ['operating-systems-core-concepts', 'dbms-sql-normalization-guide', 'digital-electronics-exam-guide'],
  },
  {
    slug: 'object-oriented-programming-guide',
    title: 'Object-Oriented Programming Exam Guide',
    description: 'A clear guide to classes, objects, inheritance, polymorphism, abstraction, encapsulation, exceptions, and common OOP answer patterns.',
    category: 'Programming',
    department: 'Computer Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Object-Oriented Programming is not only syntax. Exams test whether you can explain why classes, objects, inheritance, abstraction, and polymorphism make software easier to organize. Code snippets matter, but the concept behind each snippet matters more.',
    whyItMatters: 'Students often memorize definitions but struggle when asked to differentiate overloading and overriding, choose inheritance types, or explain dynamic dispatch. The best answers combine a short definition, a small example, and a note on when the feature is useful.',
    keyTopics: ['Classes, objects, constructors, destructors, and access specifiers', 'Encapsulation, abstraction, inheritance, and polymorphism', 'Function overloading, operator overloading, and method overriding', 'Abstract classes, interfaces, virtual functions, and dynamic binding', 'Exception handling, file handling, and templates or generics', 'Object lifetime, memory basics, and common design principles'],
    practicePlan: ['Write one small example for every core OOP pillar.', 'Prepare comparison tables for overloading vs overriding and abstract class vs interface.', 'Practice tracing constructor and destructor calls in inheritance examples.', 'Solve PYQs that ask for code plus explanation, not only definitions.', 'Revise common diagrams such as class hierarchy and object relationship diagrams.'],
    commonMistakes: ['Defining encapsulation as data hiding only and ignoring controlled access.', 'Confusing compile-time polymorphism with runtime polymorphism.', 'Using inheritance when composition would be a better design example.', 'Forgetting base-class constructor order in trace questions.', 'Writing large code blocks with no explanation.'],
    examRoomTips: ['For concept questions, use definition, example, benefit, and limitation.', 'Keep code snippets short and focused on the tested idea.', 'If asked for a difference, use a table with at least one example row.', 'Mention access specifiers whenever inheritance visibility matters.'],
    faqs: [
      { question: 'How much code should an OOP answer include?', answer: 'Use enough code to prove the concept. A small class example with comments is usually better than a long program that hides the main idea.' },
      { question: 'What is the safest way to answer polymorphism questions?', answer: 'State the two types, give one example of each, and explain how method selection happens at compile time or runtime.' },
    ],
    relatedSlugs: ['data-structures-pyq-strategy', 'dbms-sql-normalization-guide', 'operating-systems-core-concepts'],
  },
  {
    slug: 'signals-systems-problem-solving',
    title: 'Signals and Systems Problem-Solving Guide',
    description: 'A revision guide for continuous and discrete signals, LTI systems, convolution, Fourier series, Fourier transform, and Laplace transform.',
    category: 'Electronics',
    department: 'Electronics and Communication',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Signals and Systems is a method-driven subject. Most questions ask you to classify a signal, test a system property, calculate convolution, or apply a transform. The strongest revision plan is to learn the decision tests and then solve representative examples.',
    whyItMatters: 'The same signal can look confusing until you write its definition, range, periodicity, and transformation. Similarly, system properties become easier when you test them one by one: linearity, time invariance, causality, memory, stability, and invertibility.',
    keyTopics: ['Signal classification, transformations, unit impulse, unit step, and basic operations', 'System properties for continuous-time and discrete-time systems', 'Convolution integral, convolution sum, and graphical convolution', 'Fourier series and Fourier transform properties', 'Laplace transform, ROC, poles, zeros, and system stability', 'Sampling theorem, Z-transform basics, and frequency response'],
    practicePlan: ['Create a one-page property test checklist for systems.', 'Practice drawing transformed signals before calculating values.', 'Solve convolution problems using both table and graphical methods.', 'Memorize standard transform pairs and properties through daily recall.', 'Use pole-zero sketches to connect ROC and stability.'],
    commonMistakes: ['Declaring a signal periodic without calculating the fundamental period.', 'Testing linearity with only one input instead of a combined input.', 'Dropping limits during convolution integral setup.', 'Ignoring ROC in Laplace or Z-transform questions.', 'Confusing causality with stability.'],
    examRoomTips: ['For system properties, write each test as a separate line.', 'In convolution, draw or tabulate the overlap before integration or summation.', 'Mention ROC whenever transform questions include stability or causality.', 'Use symmetry properties to simplify Fourier calculations.'],
    faqs: [
      { question: 'Is convolution the most important topic?', answer: 'It is one of the most repeated numerical areas. However, system properties and transforms are equally important because they appear in short and long questions.' },
      { question: 'How should I memorize transform properties?', answer: 'Use active recall. Cover the property sheet, write what you remember, then correct it. Repeating this daily is faster than passive reading.' },
    ],
    relatedSlugs: ['digital-electronics-exam-guide', 'communication-systems-exam-guide', 'control-systems-root-locus'],
  },
  {
    slug: 'strength-of-materials-formula-map',
    title: 'Strength of Materials Formula Map',
    description: 'A formula-first revision guide for stress, strain, torsion, bending, shear force, bending moment, columns, and Mohr circle.',
    category: 'Mechanical Engineering',
    department: 'Mechanical and Civil Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Strength of Materials is formula-heavy, but formulas only help when you know the physical situation behind them. The safest exam method is to identify the member type, loading, supports, assumptions, and required output before substituting values.',
    whyItMatters: 'A well-drawn free-body diagram can decide the rest of the answer. Students who skip diagrams often choose the wrong moment expression, section property, or stress relation. Diagrams, units, and sign convention are the backbone of this subject.',
    keyTopics: ['Simple stress, strain, elastic constants, and thermal stress', 'Axial loading, compound bars, and strain energy basics', 'Shear force and bending moment diagrams', 'Bending stress, shear stress, and section modulus', 'Torsion of circular shafts and power transmission', 'Principal stresses, Mohr circle, columns, and buckling'],
    practicePlan: ['Build a formula sheet grouped by loading case and member type.', 'Practice drawing SFD and BMD for standard support-load combinations.', 'Solve one bending stress and one torsion numerical every day for a week.', 'Create a unit checklist for N, mm, m, MPa, and GPa conversions.', 'Revise Mohr circle with three examples: uniaxial, biaxial, and shear-included.'],
    commonMistakes: ['Using diameter instead of radius in polar moment calculations.', 'Mixing millimeters and meters in bending or torsion formulas.', 'Drawing shear force diagrams without checking equilibrium.', 'Using Euler column formula outside its valid assumptions.', 'Forgetting sign convention for sagging and hogging moments.'],
    examRoomTips: ['Draw the member and loading before writing equations.', 'Write section properties separately so they can be checked easily.', 'For SFD and BMD, calculate reactions first and verify total force balance.', 'Mark maximum stress or maximum moment clearly in the final answer.'],
    faqs: [
      { question: 'What should I memorize first?', answer: 'Start with stress-strain relations, bending equation, torsion equation, section properties, and Euler column formula. Then practice choosing the right one.' },
      { question: 'How do I improve SFD and BMD?', answer: 'Practice standard cases repeatedly and always verify reactions. Most mistakes start before the diagram is even drawn.' },
    ],
    relatedSlugs: ['thermodynamics-numerical-practice', 'fluid-mechanics-exam-prep', 'machine-design-safe-practice'],
  },
  {
    slug: 'fluid-mechanics-exam-prep',
    title: 'Fluid Mechanics Exam Preparation Guide',
    description: 'A revision guide for fluid properties, pressure, buoyancy, Bernoulli equation, flow measurement, pipe losses, and dimensional analysis.',
    category: 'Mechanical Engineering',
    department: 'Mechanical and Civil Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Fluid Mechanics questions become easier when you visualize the flow before solving. Is the fluid static or moving? Is the flow steady or unsteady? Is energy loss considered? These decisions determine which equation is valid.',
    whyItMatters: 'The most common error is applying Bernoulli equation without checking assumptions. A good answer states the selected points, datum, pressure terms, velocity terms, head loss if applicable, and units. This clarity earns marks even in long numerical problems.',
    keyTopics: ['Fluid properties, viscosity, surface tension, and capillarity', 'Pressure measurement, manometers, hydrostatic forces, and buoyancy', 'Continuity equation, Bernoulli equation, and energy correction basics', 'Venturimeter, orifice meter, pitot tube, and flow measurement', 'Laminar and turbulent flow, Reynolds number, and pipe losses', 'Dimensional analysis, model testing, pumps, and turbines basics'],
    practicePlan: ['Memorize unit dimensions for pressure, viscosity, discharge, and head.', 'Practice manometer problems with a consistent pressure-level method.', 'Solve Bernoulli questions by marking point 1, point 2, and datum line.', 'Group pipe-loss problems by minor loss, major loss, and equivalent length.', 'Practice dimensional analysis with repeating variables until Pi terms feel natural.'],
    commonMistakes: ['Using pressure units and head units in the same equation without conversion.', 'Forgetting datum head in Bernoulli problems.', 'Applying laminar formulas when the Reynolds number indicates turbulent flow.', 'Missing discharge coefficient in flow measurement devices.', 'Choosing repeating variables incorrectly in dimensional analysis.'],
    examRoomTips: ['Draw tanks, pipes, and measuring devices clearly.', 'Write assumptions such as incompressible, steady, and inviscid only when valid.', 'Check whether the answer asks for pressure, pressure head, velocity, discharge, or power.', 'For dimensional analysis, show the dimension matrix or equation steps neatly.'],
    faqs: [
      { question: 'Is Bernoulli equation enough for most numericals?', answer: 'It is central, but not enough by itself. Many problems also require continuity, losses, coefficients, or pump/turbine terms.' },
      { question: 'How can I remember pipe-loss formulas?', answer: 'Group them by physical cause: friction over length, entrance, exit, bend, sudden expansion, and sudden contraction. The grouping helps recall.' },
    ],
    relatedSlugs: ['thermodynamics-numerical-practice', 'strength-of-materials-formula-map', 'environmental-engineering-notes'],
  },
  {
    slug: 'microprocessors-8086-revision',
    title: '8086 Microprocessor Revision Guide',
    description: 'A clear revision guide for 8086 architecture, registers, addressing modes, instruction set, interrupts, timing, and assembly programs.',
    category: 'Electronics',
    department: 'Electronics and Communication',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: '8086 revision works best when architecture and programming are studied together. Registers, segments, flags, addressing modes, and interrupts are not separate facts; they explain how an assembly program moves data and controls execution.',
    whyItMatters: 'Many exam answers require diagrams and short programs. A labeled architecture diagram, flag register explanation, and clean assembly steps can score well even if the program is short. The key is to show intent: input, operation, output, and affected flags.',
    keyTopics: ['8086 architecture, BIU, EU, registers, flags, and memory segmentation', 'Addressing modes and physical address calculation', 'Instruction set: data transfer, arithmetic, logical, branch, and string instructions', 'Assembler directives, procedures, macros, and stack operations', 'Interrupts, interrupt vector table, and basic interfacing concepts', 'Timing diagrams, minimum and maximum mode basics'],
    practicePlan: ['Draw the 8086 block diagram from memory until labels are complete.', 'Practice physical address calculations with segment and offset values.', 'Write short assembly programs for addition, subtraction, sorting, and string operations.', 'Create a table of common instructions and affected flags.', 'Revise interrupts with the sequence of events and vector table structure.'],
    commonMistakes: ['Confusing segment address with physical address.', 'Forgetting that physical address equals segment times 10H plus offset.', 'Writing assembly code without comments for registers used.', 'Ignoring carry, zero, sign, and overflow flags in arithmetic explanations.', 'Mixing minimum and maximum mode signal names.'],
    examRoomTips: ['For programs, write algorithm steps before assembly instructions.', 'Use comments to explain register purpose.', 'For architecture questions, draw first and explain each block after the diagram.', 'Show flag changes when the question involves arithmetic or comparison.'],
    faqs: [
      { question: 'Do I need to memorize every instruction?', answer: 'No. Focus on common instruction groups and know how to explain their purpose. Practice common program patterns from PYQs.' },
      { question: 'What is the best way to revise addressing modes?', answer: 'Make one example for each mode and calculate the effective address. Examples are easier to remember than definitions alone.' },
    ],
    relatedSlugs: ['digital-electronics-exam-guide', 'communication-systems-exam-guide', 'circuit-analysis-semester-revision'],
  },
  {
    slug: 'environmental-engineering-notes',
    title: 'Environmental Engineering Notes Guide',
    description: 'A practical guide to water treatment, wastewater treatment, air pollution control, solid waste management, and sustainability topics.',
    category: 'Civil Engineering',
    department: 'Civil Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Environmental Engineering combines process understanding with standards, diagrams, and real-world applications. Students should revise it as a sequence of treatment decisions: what impurity exists, why it matters, which unit process removes it, and how performance is checked.',
    whyItMatters: 'Long answers are stronger when they include flow diagrams. Whether the topic is water treatment, wastewater treatment, air pollution, or solid waste, a process-flow answer helps reviewers see that you understand order and purpose.',
    keyTopics: ['Water demand, sources, quality parameters, and drinking water standards', 'Coagulation, sedimentation, filtration, disinfection, and distribution basics', 'Wastewater characteristics, primary, secondary, and tertiary treatment', 'BOD, COD, DO, sludge digestion, and activated sludge process', 'Air pollution sources, control devices, and particulate removal', 'Solid waste collection, disposal, composting, landfill, and sustainability'],
    practicePlan: ['Draw complete water and wastewater treatment flow diagrams from memory.', 'Create a parameter table for pH, turbidity, hardness, BOD, COD, and DO.', 'Practice numerical questions on water demand, BOD, and treatment efficiency.', 'Revise air pollution control devices with diagrams and use cases.', 'Prepare short notes on sustainability, reuse, and public health relevance.'],
    commonMistakes: ['Listing treatment units without explaining their purpose.', 'Confusing BOD and COD meaning.', 'Forgetting units in concentration and demand calculations.', 'Drawing flow diagrams in the wrong order.', 'Writing generic pollution answers without linking to control methods.'],
    examRoomTips: ['Use flow charts for process questions.', 'Include one practical example for public-health questions.', 'For numerical answers, write units and assumptions clearly.', 'In pollution-control comparisons, mention pollutant type, device, efficiency, and limitation.'],
    faqs: [
      { question: 'Are standards important for exams?', answer: 'Yes, but memorize only the key values your syllabus emphasizes. Understanding what each parameter indicates is more important than memorizing every number.' },
      { question: 'How do I make long answers better?', answer: 'Start with a definition, add a flow diagram, explain each step briefly, and end with advantages or limitations.' },
    ],
    relatedSlugs: ['fluid-mechanics-exam-prep', 'construction-materials-practical-guide', 'study-planner-active-recall'],
  },
  {
    slug: 'control-systems-root-locus',
    title: 'Control Systems Root Locus and Stability Guide',
    description: 'A focused guide for transfer functions, block diagrams, time response, Routh stability, root locus, frequency response, and controllers.',
    category: 'Electrical Engineering',
    department: 'Electrical and Electronics',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Control Systems links mathematics with engineering behavior. The central question is how a system responds and whether it remains stable. Root locus, Routh criterion, Bode plots, and time-response specifications are tools for answering that question.',
    whyItMatters: 'Students often memorize procedures without understanding what the plot or table means. A better solution states what stability or transient behavior is being tested, performs the procedure, and interprets the result in words.',
    keyTopics: ['Transfer functions, poles, zeros, and standard test inputs', 'Block diagram reduction and signal flow graphs', 'Time response, steady-state error, damping ratio, and natural frequency', 'Routh-Hurwitz stability criterion and special cases', 'Root locus rules, breakaway points, asymptotes, and angle condition', 'Bode plots, Nyquist basics, gain margin, phase margin, and controllers'],
    practicePlan: ['Practice block reduction until equivalent transfer functions are accurate.', 'Solve Routh tables with at least two special-case examples.', 'Draw root locus by following rules in a fixed order.', 'Create a formula sheet for time-domain specifications.', 'Practice Bode magnitude and phase sketches using standard factors.'],
    commonMistakes: ['Forgetting sign conventions in feedback transfer functions.', 'Skipping special cases in Routh criterion.', 'Drawing root locus branches without checking real-axis segments.', 'Confusing gain margin and phase margin.', 'Writing controller benefits without linking them to system response.'],
    examRoomTips: ['For root locus, list poles, zeros, centroid, asymptotes, and real-axis segments before drawing.', 'In Routh problems, state the stability condition from the first column.', 'For Bode plots, build the sketch factor by factor.', 'End stability answers with a clear stable, marginal, or unstable conclusion.'],
    faqs: [
      { question: 'Is root locus hard to score?', answer: 'It scores well if you follow the rules in order. Even an imperfect drawing can earn marks when calculations are shown clearly.' },
      { question: 'Should I prioritize Routh or Bode plots?', answer: 'Both are common. Routh is faster for stability decisions, while Bode plots test frequency-response understanding.' },
    ],
    relatedSlugs: ['circuit-analysis-semester-revision', 'signals-systems-problem-solving', 'power-systems-revision-guide'],
  },
  {
    slug: 'machine-design-safe-practice',
    title: 'Machine Design Safe Practice Guide',
    description: 'A revision guide for design stresses, factor of safety, shafts, keys, couplings, springs, gears, bearings, and failure theories.',
    category: 'Mechanical Engineering',
    department: 'Mechanical Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Machine Design is about choosing dimensions and materials that work safely under load. The subject can feel formula-heavy, but every formula is connected to failure prevention, stiffness, wear, fatigue, or service conditions.',
    whyItMatters: 'Examiners look for assumptions and design decisions. A numerical answer should include material properties, factor of safety, failure criterion, load type, and final selected standard size if the question asks for design rather than analysis.',
    keyTopics: ['Design process, stress concentration, factor of safety, and design codes', 'Static and dynamic loading, fatigue, endurance limit, and failure theories', 'Shaft design under bending and torsion', 'Keys, cotters, knuckle joints, riveted joints, and welded joints', 'Springs, clutches, brakes, bearings, and lubrication basics', 'Gear terminology, beam strength, wear strength, and gear design checks'],
    practicePlan: ['Make a decision chart for choosing static or fatigue design equations.', 'Practice shaft problems with combined bending and torsion.', 'Solve joint design questions by checking each possible failure mode.', 'Create a table of standard assumptions and correction factors from your syllabus.', 'Revise gear and bearing problems using stepwise design sheets.'],
    commonMistakes: ['Using ultimate strength instead of allowable stress without factor of safety.', 'Checking only one failure mode in joint design.', 'Ignoring keyway weakening in shaft problems.', 'Confusing static load rating with dynamic load rating for bearings.', 'Leaving the final answer as an exact decimal instead of selecting a practical size.'],
    examRoomTips: ['State assumptions before calculations.', 'For design problems, calculate and then choose the next safe standard size.', 'Check all failure modes requested by the problem.', 'Use diagrams to mark forces, dimensions, and critical sections.'],
    faqs: [
      { question: 'How do I know which failure theory to use?', answer: 'Follow your syllabus guidance and material type. Ductile materials often use maximum shear stress or distortion energy theory; brittle materials often use maximum principal stress theory.' },
      { question: 'Why do my answers differ from solved examples?', answer: 'Design problems can vary due to selected factors and standard sizes. Show assumptions clearly so your method is visible.' },
    ],
    relatedSlugs: ['strength-of-materials-formula-map', 'thermodynamics-numerical-practice', 'fluid-mechanics-exam-prep'],
  },
  {
    slug: 'power-systems-revision-guide',
    title: 'Power Systems Revision Guide',
    description: 'A revision guide for generation, transmission, distribution, per-unit calculations, faults, load flow basics, and protection.',
    category: 'Electrical Engineering',
    department: 'Electrical Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Power Systems connects machines, networks, economics, and protection. The subject becomes manageable when you divide it into generation, transmission, distribution, analysis, and protection rather than reading it as one large block.',
    whyItMatters: 'Many questions require both conceptual explanation and calculation. Transmission-line performance, per-unit conversion, fault analysis, and tariff problems all reward a clear sequence of known values, base values, equations, and interpretation.',
    keyTopics: ['Power generation methods, load curve, load factor, and plant economics', 'Transmission line parameters, short, medium, and long line models', 'Corona, sag, insulators, and mechanical design basics', 'Per-unit system, symmetrical components, and fault analysis basics', 'Distribution systems, substations, earthing, and power factor correction', 'Protection devices, relays, circuit breakers, and load-flow introduction'],
    practicePlan: ['Create separate sheets for formulas, diagrams, and protection devices.', 'Practice per-unit conversion until base changes are comfortable.', 'Solve line-performance numericals with consistent phase or line values.', 'Draw protection scheme diagrams and label each device function.', 'Use PYQs to identify repeated generation economics and transmission topics.'],
    commonMistakes: ['Mixing line and phase quantities in three-phase calculations.', 'Forgetting base-value conversion in per-unit problems.', 'Writing relay names without explaining their protection purpose.', 'Ignoring units in tariff and load-factor calculations.', 'Skipping phasor diagrams in transmission-line answers.'],
    examRoomTips: ['Write base values before per-unit calculations.', 'For line models, state whether the line is short, medium, or long.', 'Use labeled diagrams for substations and protection schemes.', 'End economics problems with units such as kWh, kW, and cost per unit.'],
    faqs: [
      { question: 'Is per-unit system difficult?', answer: 'It becomes simple with repetition. Always identify old base, new base, and whether voltage or power base is changing.' },
      { question: 'How should I revise protection?', answer: 'Make a device-purpose table. For each relay or breaker, write what fault it detects, where it is used, and one limitation.' },
    ],
    relatedSlugs: ['circuit-analysis-semester-revision', 'control-systems-root-locus', 'machine-design-safe-practice'],
  },
  {
    slug: 'communication-systems-exam-guide',
    title: 'Communication Systems Exam Guide',
    description: 'A focused guide for analog modulation, digital modulation, noise, sampling, multiplexing, information theory, and link basics.',
    category: 'Electronics',
    department: 'Electronics and Communication',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 8,
    summary: 'Communication Systems questions test how information is represented, transmitted, affected by noise, and recovered. The subject becomes clearer when every modulation method is studied by comparing bandwidth, power, complexity, and noise performance.',
    whyItMatters: 'Students often memorize modulation definitions but cannot explain why a method is chosen. A strong answer links waveform, spectrum, bandwidth, transmitter or receiver block diagram, and practical advantage.',
    keyTopics: ['Amplitude modulation, DSB-SC, SSB, VSB, and AM transmitters/receivers', 'Angle modulation, FM, PM, bandwidth, and noise performance', 'Sampling theorem, quantization, PCM, delta modulation, and multiplexing', 'Digital modulation such as ASK, FSK, PSK, QPSK, and QAM basics', 'Noise, SNR, channel capacity, entropy, and information theory basics', 'Antennas, propagation, link budget, and modern communication overview'],
    practicePlan: ['Draw transmitter and receiver block diagrams for AM, FM, and PCM.', 'Practice bandwidth calculations for modulation types.', 'Create comparison tables for analog and digital modulation methods.', 'Solve SNR and channel-capacity numericals from PYQs.', 'Revise waveforms and spectra together so diagrams match explanations.'],
    commonMistakes: ['Confusing modulation index definitions for AM and FM.', 'Forgetting sidebands and bandwidth in spectrum questions.', 'Writing sampling theorem without mentioning Nyquist rate.', 'Mixing bit rate and baud rate.', 'Drawing block diagrams without labeling inputs and outputs.'],
    examRoomTips: ['For each modulation answer, include equation, waveform or spectrum, bandwidth, and use case.', 'Use tables for ASK, FSK, PSK, and QAM comparison.', 'In numerical questions, keep logarithmic units clear.', 'When asked for advantages, mention noise immunity, bandwidth, power, or circuit complexity.'],
    faqs: [
      { question: 'Which diagrams should I practice?', answer: 'AM transmitter/receiver, FM generation/detection, PCM system, sampling waveform, and digital modulation constellation diagrams are high-value diagrams.' },
      { question: 'How do I remember bandwidth formulas?', answer: 'Group them by modulation family and solve examples. Formulas become easier when connected to sidebands and frequency deviation.' },
    ],
    relatedSlugs: ['signals-systems-problem-solving', 'digital-electronics-exam-guide', 'microprocessors-8086-revision'],
  },
  {
    slug: 'construction-materials-practical-guide',
    title: 'Construction Materials Practical Guide',
    description: 'A civil engineering revision guide for cement, aggregates, concrete, bricks, steel, timber, tests, and site-quality checks.',
    category: 'Civil Engineering',
    department: 'Civil Engineering',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'Construction Materials is practical by nature. The best answers connect material properties to construction decisions: strength, durability, workability, cost, availability, and site conditions. This makes theory answers less generic and more examiner-friendly.',
    whyItMatters: 'Many students list properties but do not explain why they matter. For example, aggregate grading affects workability and strength, water-cement ratio affects durability, and curing affects hydration. Linking property to performance creates stronger answers.',
    keyTopics: ['Cement composition, hydration, tests, grades, and storage', 'Fine and coarse aggregates, grading, bulking, and tests', 'Concrete ingredients, water-cement ratio, workability, compaction, curing, and strength', 'Bricks, blocks, stones, timber, steel, and bituminous materials', 'Admixtures, special concretes, and durability considerations', 'Field tests, lab tests, quality control, and sustainable materials'],
    practicePlan: ['Create property-purpose tables for cement, aggregate, concrete, brick, and steel.', 'Practice standard test procedures with aim, apparatus, steps, and result format.', 'Revise water-cement ratio and curing through practical examples.', 'Draw flow charts for concrete production, placement, compaction, and curing.', 'Use site-quality scenarios to test whether you can choose the right material.'],
    commonMistakes: ['Listing material properties without explaining their effect.', 'Confusing workability with strength.', 'Forgetting curing importance in concrete answers.', 'Writing test names without procedure or interpretation.', 'Ignoring durability and environmental exposure in material selection.'],
    examRoomTips: ['Use tables for material comparison questions.', 'For test procedures, write aim, apparatus, procedure, observation, and result.', 'Mention field relevance in long answers.', 'Use simple sketches for slump test, aggregate grading, or brick bonds when useful.'],
    faqs: [
      { question: 'Are lab-test steps important?', answer: 'Yes. Many exams ask procedures directly, and even theory questions improve when you mention how a property is measured.' },
      { question: 'How do I write better concrete answers?', answer: 'Always connect mix ingredients, water-cement ratio, workability, compaction, curing, and final strength. These ideas belong together.' },
    ],
    relatedSlugs: ['environmental-engineering-notes', 'fluid-mechanics-exam-prep', 'strength-of-materials-formula-map'],
  },
  {
    slug: 'study-planner-active-recall',
    title: 'Active Recall Study Planner for Engineering Students',
    description: 'A practical planning guide for active recall, spaced repetition, weekly targets, mock tests, and exam-week revision.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'A study plan is useful only when it changes how you practice. Active recall means testing yourself before you feel ready, while spaced repetition means reviewing just often enough to prevent forgetting. Together, they turn revision from reading into retrieval.',
    whyItMatters: 'Many students create beautiful timetables but still revise passively. A better planner assigns outcomes: solve ten PYQs, recall five derivations, explain one topic aloud, write one formula sheet from memory, or complete one timed mock.',
    keyTopics: ['Weekly planning, daily target setting, and prioritization', 'Active recall prompts, blurting, flashcards, and closed-book summaries', 'Spaced repetition intervals and revision calendars', 'PYQ tagging, mock tests, and error logs', 'Energy management, sleep, breaks, and attention control', 'Exam-week consolidation and last-day checklist'],
    practicePlan: ['List every subject and rank topics as strong, medium, or weak.', 'Convert each weak topic into a recall task rather than a reading task.', 'Review topics after one day, three days, seven days, and fourteen days where possible.', 'Maintain an error log with mistake, correction, and next review date.', 'Schedule mock tests early enough to fix weaknesses, not only to measure them.'],
    commonMistakes: ['Planning by hours instead of outcomes.', 'Re-reading highlighted notes and assuming the topic is learned.', 'Skipping sleep to add study time, then losing recall quality.', 'Taking mock tests without reviewing mistakes.', 'Studying easy topics repeatedly because they feel comfortable.'],
    examRoomTips: ['Use the last 24 hours for recall sheets, marked PYQs, and error log review.', 'Avoid starting large new chapters unless they are unavoidable.', 'Pack exam materials early and keep sleep consistent.', 'Before the paper starts, breathe slowly and scan the question paper once.'],
    faqs: [
      { question: 'How many hours should I study daily?', answer: 'The better question is what outcomes you complete. Four focused hours with recall and PYQs can beat eight distracted hours of passive reading.' },
      { question: 'What should I do after a bad mock test?', answer: 'Treat it as data. Mark every mistake by type: concept, formula, careless calculation, time management, or presentation. Then revise the highest-frequency mistake first.' },
    ],
    relatedSlugs: ['engineering-mathematics-revision-plan', 'data-structures-pyq-strategy', 'exam-writing-answer-presentation'],
  },
  {
    slug: 'exam-writing-answer-presentation',
    title: 'Exam Writing and Answer Presentation Guide',
    description: 'A practical guide to structuring long answers, diagrams, derivations, numericals, tables, and time management during semester exams.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 6,
    summary: 'Good preparation can lose marks if answers are hard to read. Presentation does not mean decoration; it means the examiner can quickly see your method, diagrams, assumptions, formulas, final answer, and conclusion.',
    whyItMatters: 'Engineering papers often use step marking. A clean structure protects marks when the final answer is incomplete. It also reduces review time because you can find errors in your own work more easily.',
    keyTopics: ['Time allocation across sections and marks', 'Long-answer structure: definition, diagram, explanation, advantages, limitations', 'Numerical structure: data, formula, substitution, calculation, units, final answer', 'Diagram labeling, tables, flowcharts, and comparison answers', 'Derivation layout and assumption writing', 'Final revision, rechecking, and avoiding avoidable presentation errors'],
    practicePlan: ['Before each mock, decide time per mark and follow it strictly.', 'Practice writing one-page long answers with headings and diagrams.', 'Use tables for comparison questions instead of paragraphs.', 'For numericals, always write given data and units before equations.', 'Reserve the final five to ten minutes for checking units, signs, and unanswered subparts.'],
    commonMistakes: ['Writing a long paragraph when a labeled diagram would be clearer.', 'Skipping assumptions in derivations.', 'Not boxing final numerical answers.', 'Spending too much time on a low-mark question.', 'Leaving answers unlabeled when the question has multiple parts.'],
    examRoomTips: ['Answer the questions you know best first if the paper allows choice.', 'Use headings that match the question words.', 'Keep diagrams large enough to label clearly.', 'When time is low, write key formulas, steps, and final conclusion rather than a blank page.'],
    faqs: [
      { question: 'Should I use colored pens?', answer: 'Follow your exam rules. A single blue or black pen with underlining and clear spacing is usually enough.' },
      { question: 'How do I handle a question I partly know?', answer: 'Write the definition, diagram, relevant formula, and whatever valid steps you know. Partial knowledge presented clearly can still earn marks.' },
    ],
    relatedSlugs: ['study-planner-active-recall', 'engineering-mathematics-revision-plan', 'data-structures-pyq-strategy'],
  },
  {
    slug: 'pyq-analysis-how-to-find-repeated-topics',
    title: 'How to Analyze PYQs and Find Repeated Topics',
    description: 'A method for tagging previous year questions, finding repeated patterns, ranking topics, and turning PYQs into a revision plan.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'PYQs are most powerful when they are analyzed, not just solved. Repeated topics, repeated command words, and repeated numerical formats show what the examiner expects students to understand. This guide turns PYQs into a practical revision map.',
    whyItMatters: 'Without analysis, students may solve papers randomly and miss the pattern. With analysis, each question becomes evidence: which topic appears, what depth is required, whether the answer is diagram-based or numerical, and how marks are distributed.',
    keyTopics: ['Collecting papers and organizing them by subject, year, and exam type', 'Tagging every question by topic, subtopic, marks, and command word', 'Identifying repeated diagrams, derivations, numericals, and comparisons', 'Ranking topics by frequency, difficulty, and confidence', 'Creating a revision timetable from the PYQ map', 'Using mock tests to validate the pattern without depending on it blindly'],
    practicePlan: ['Create a spreadsheet or notebook table for all available PYQs.', 'Use consistent tags such as definition, derivation, diagram, numerical, and comparison.', 'Mark topics that appeared in three or more papers as high priority.', 'Solve high-frequency questions first, then medium-frequency weak topics.', 'After each mock test, update your confidence score for each topic.'],
    commonMistakes: ['Assuming repeated topics guarantee the next paper.', 'Solving papers without tagging why each question matters.', 'Ignoring low-frequency topics that are easy and scoring.', 'Not separating short-answer patterns from long-answer patterns.', 'Copying solutions without attempting them first.'],
    examRoomTips: ['Use PYQ analysis to choose revision order, not to make risky guesses.', 'During the paper, recognize familiar patterns but still read the exact wording.', 'When a repeated topic appears in a new form, answer the concept instead of forcing an old solution.', 'Keep your final revision list short enough to actually complete.'],
    faqs: [
      { question: 'How many years of PYQs should I analyze?', answer: 'Five years is a strong baseline. If the subject has fewer available papers, add class tests, model papers, and assignments.' },
      { question: 'Can I skip topics that never appeared?', answer: 'Be careful. Use frequency as one factor, but also consider syllabus importance, teacher emphasis, and how easy the topic is to prepare.' },
    ],
    relatedSlugs: ['study-planner-active-recall', 'exam-writing-answer-presentation', 'engineering-mathematics-revision-plan'],
  },
  {
    slug: 'lab-file-viva-preparation',
    title: 'Lab File and Viva Preparation Guide',
    description: 'A practical guide for preparing lab files, experiment records, circuit diagrams, observations, results, and viva answers.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 6,
    summary: 'Lab work is not only about completing records. A good lab file shows that you understand aim, apparatus, theory, procedure, observations, calculations, result, precautions, and sources of error. Viva preparation should follow the same structure.',
    whyItMatters: 'Students often prepare viva by memorizing random questions. A better method is to understand each experiment as a flow: why it is done, what is measured, how it is measured, what can go wrong, and what the result means.',
    keyTopics: ['Lab-file structure and clean observation tables', 'Aim, apparatus, theory, circuit or setup diagram, and procedure', 'Calculations, graphs, result writing, and error discussion', 'Precautions, safety, and instrument handling', 'Common viva question types and concise answer practice', 'Submission checklist and academic-integrity expectations'],
    practicePlan: ['Review every experiment and write its purpose in one sentence.', 'Redraw diagrams neatly and label all instruments or components.', 'Practice explaining the procedure aloud without reading.', 'Prepare five likely viva questions per experiment.', 'Check observation units, graph labels, and final result format before submission.'],
    commonMistakes: ['Copying theory without understanding the experiment.', 'Submitting observation tables with missing units.', 'Drawing unlabeled circuit diagrams or apparatus diagrams.', 'Ignoring precautions and sources of error.', 'Giving long viva answers when a precise answer is better.'],
    examRoomTips: ['In viva, answer directly first and then add explanation if asked.', 'If you do not know an answer, state what you know related to the concept instead of guessing wildly.', 'For practical exams, keep calculations organized and preserve raw observations.', 'Mention safety and calibration where relevant.'],
    faqs: [
      { question: 'How should I prepare viva in one day?', answer: 'Focus on aim, principle, key formula, apparatus function, procedure, result, and two precautions for each experiment.' },
      { question: 'Is handwriting important in lab files?', answer: 'Readability matters. Neat structure, correct units, and complete diagrams are more important than decorative writing.' },
    ],
    relatedSlugs: ['exam-writing-answer-presentation', 'pyq-analysis-how-to-find-repeated-topics', 'study-planner-active-recall'],
  },
  {
    slug: 'first-year-engineering-survival-guide',
    title: 'First Year Engineering Survival Guide',
    description: 'A practical guide for first-year students covering lectures, labs, mathematics, programming, attendance, notes, and exam habits.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'First year can feel scattered because students must manage new subjects, labs, attendance, assignments, and semester exams at the same time. The goal is not to study all day; the goal is to build routines that make exam season less chaotic.',
    whyItMatters: 'Most first-year academic trouble starts small: missed lectures, incomplete lab records, unorganized notes, and delayed math practice. Fixing these habits early makes later semesters easier because core subjects depend on the same discipline.',
    keyTopics: ['Weekly lecture review and note organization', 'Engineering mathematics and programming practice habits', 'Lab-file completion and viva basics', 'Attendance, deadlines, assignments, and internal marks', 'Using PYQs without depending only on repeated questions', 'Building peer study groups and asking for help early'],
    practicePlan: ['Review each lecture within 24 hours and write three recall questions.', 'Practice mathematics problems in short daily sessions instead of one long weekly session.', 'Keep lab records updated the same week as the experiment.', 'Make a deadline calendar for assignments, internals, and practical work.', 'Solve one previous paper before each internal test to understand question style.'],
    commonMistakes: ['Waiting until exams to organize notes.', 'Ignoring labs because theory exams feel more urgent.', 'Copying assignments without understanding the method.', 'Treating attendance and internal marks as separate from final performance.', 'Studying alone when a doubt could be solved quickly by asking.'],
    examRoomTips: ['Before every test, revise formulas, definitions, diagrams, and one solved example per topic.', 'Attempt familiar questions first and keep handwriting readable.', 'For programming or math, show steps even when the final answer is incomplete.', 'After each exam, write down what preparation worked and what needs change.'],
    faqs: [
      { question: 'How should I balance all first-year subjects?', answer: 'Use small daily blocks. Math and programming need frequent practice, while theory subjects need weekly recall and diagrams.' },
      { question: 'When should I start using PYQs?', answer: 'Use them after basic concept coverage. PYQs are best for understanding question patterns, not as a replacement for learning.' },
    ],
    relatedSlugs: ['study-planner-active-recall', 'lab-file-viva-preparation', 'exam-writing-answer-presentation'],
  },
  {
    slug: 'semester-backlog-recovery-plan',
    title: 'Semester Backlog Recovery Plan',
    description: 'A calm and practical recovery plan for students preparing for a backlog, reappear, or repeat semester paper.',
    category: 'Study Skills',
    department: 'All Branches',
    author: DEFAULT_AUTHOR,
    updatedAt: CONTENT_UPDATED_AT,
    readingMinutes: 7,
    summary: 'A backlog can feel discouraging, but it is a solvable academic problem when approached systematically. The key is to stop treating the whole subject as one large fear and break it into repeated topics, scoring units, weak fundamentals, and timed practice.',
    whyItMatters: 'Backlog preparation often fails because students either over-study without direction or avoid the subject until the final week. A recovery plan gives you a visible path: diagnose, prioritize, practice, test, and revise.',
    keyTopics: ['Understanding the syllabus and marking scheme', 'Collecting PYQs, class notes, assignments, and solved examples', 'Separating high-frequency topics from foundation topics', 'Building a compact formula, definition, and diagram notebook', 'Timed answer writing and mock-paper review', 'Managing stress, consistency, and realistic daily targets'],
    practicePlan: ['Start with a diagnostic paper and mark questions as known, partial, or unknown.', 'Prepare high-frequency topics first, but include fundamentals needed to solve them.', 'Study in two daily blocks: concept repair and PYQ practice.', 'Keep a mistake log and revise it every third day.', 'Attempt at least two full timed papers before the exam.'],
    commonMistakes: ['Trying to reread the entire textbook without solving questions.', 'Avoiding mock tests because they feel uncomfortable.', 'Skipping fundamentals required for repeated numericals.', 'Studying only easy chapters to feel productive.', 'Letting shame or comparison reduce consistency.'],
    examRoomTips: ['Attempt sure questions first to build momentum.', 'Write structured partial answers for topics you partly know.', 'Do not spend too long trying to perfect one answer.', 'Use diagrams, formulas, and definitions to secure method marks wherever possible.'],
    faqs: [
      { question: 'Can I clear a backlog with limited time?', answer: 'Yes, if the plan is focused. Prioritize repeated topics, core formulas, diagrams, and timed writing instead of passive reading.' },
      { question: 'How do I stay consistent?', answer: 'Use small daily targets and track completed outcomes. Consistency improves when progress is visible and realistic.' },
    ],
    relatedSlugs: ['pyq-analysis-how-to-find-repeated-topics', 'study-planner-active-recall', 'exam-writing-answer-presentation'],
  },
];

export const getStudyGuideBySlug = (slug: string | undefined) =>
  STUDY_GUIDES.find((guide) => guide.slug === slug);

export const getRelatedGuides = (guide: StudyGuide) =>
  guide.relatedSlugs
    .map((slug) => getStudyGuideBySlug(slug))
    .filter((related): related is StudyGuide => Boolean(related));
